---
title: "pv-reorg"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# Load libraries
library(here)
library(tidyverse)
library(janitor)
```

```{r}
# Define the folder containing the CSV files
pv_raw_data_folder <- here("data/pv-multipliers-raw")
pv_modified_data_folder <- here("data/pv-multipliers-modified")
pv_pce_data_folder <- here("data/pv-pce")
```

```{r}
# Define the correct order of the rows
correct_order <- c(
  "Agriculture",
  "Mining",
  "Construction",
  "Construction: Non-residential",
  "Construction: residential",
  "Manufacturing",
  "Fabricated metals",
  "Machinery",
  "Electrical Equip",
  "Battery Manufacturing",
  "Energy Wire Manufacturing",
  "Wholesale Trade",
  "Retail Trade",
  "TPCU",
  "Insurance and Real Estate",
  "Finance",
  "Other Professional Services",
  "Office Services",
  "Architectural and Engineering Services",
  "Other Services",
  "Government",
  "Semiconductor (solar cell/module) manufacturing"
)
```

```{r}
# Get a list of all CSV files in the data folder
csv_files <- list.files(pv_raw_data_folder, pattern = "\\.csv$", full.names = TRUE)

```

```{r}
# Loop through each CSV file
for (file in csv_files) {
    cat("Processing file: ", file, "\n")
  # Read the CSV file
  data <- read.csv(file)
    
    # Sort the data based on the correct_order
    data <- data[match(correct_order, data$Display.Description), ]

     modified_file <- gsub("\\.csv$", "_m.csv", basename(file))  # Add a suffix to the file name
     
     file_path <- file.path(pv_modified_data_folder, modified_file)
     
  write.csv(data, file_path, row.names = FALSE)
  
}

```

# ```{r}
# # New list of only pce normalized files
# norm_csv_files <- list.files(pv_pce_data_folder, pattern = "\\-norm.csv$", full.names = TRUE)
# ```
# 
# ```{r}
# # Loop through each CSV file
# for (file in norm_csv_files) {
#     cat("Processing file: ", file, "\n")
#   # Read the CSV file
#   data <- read.csv(file)
#     
#     # Sort the data based on the correct_order
#     data <- data[match(correct_order, data$household_code), ]
# 
#     # Write the modified data back to the same CSV file
#   #   modified_file <- gsub("\\.csv$", "_m.csv", file)  # Add a suffix to the file name
#  
#      write.csv(data, , row.names = FALSE)
#   
#   cat("Saved modified data to:", modified_file, "\n")
# }
# 
# ```


